In [1]:
import pandas as pd
import numpy as np

In [32]:
oct = pd.read_csv('octubre.csv')

In [27]:
oct.columns

Index(['CLIENTE', 'BANCO', 'NRO CH/', 'F.EMIS', 'F.COBRO', 'IMPORTE',
       'INTERESES', 'NETO ', 'RECIBIDO', 'FECHA PAGO', 'T', 'E', 'M',
       'DESCARGA', 'DESTINO', 'COSTO', 'EN CARTERA', 'Mes Ch'],
      dtype='object')

In [28]:
oct

,CLIENTE,BANCO,NRO CH/,F.EMIS,F.COBRO,IMPORTE,INTERESES,NETO,RECIBIDO,FECHA PAGO,T,E,M,DESCARGA,DESTINO,COSTO,EN CARTERA,Mes Ch
Pocho,Macro,33342285.0,13/05/2022,15/11/2022,165.00,0,16.225,0,148.775,0,13-oct,NaN,NaN,10/11/2022,rm,NaN,NaN,11
Pocho,Bancor,32997251.0,11/10/2022,7/11/2022,550.00,0,43.817,0,506.183,0,13-oct,NaN,NaN,21/10/2022,RM Gordo,16500,$ -,11
Pocho,Santander,24200791.0,6/10/2022,9/11/2022,650.00,0,54.817,0,595.183,0,13-oct,NaN,NaN,21/10/2022,RM Gordo,19500,$ -,11
JL,BNA,441616.0,NaN,NaN,286.00,0,3.715,0,282.285,0,NaN,NaN,NaN,18/10/2022,JALIL,7150,$ -,12
JL,BNA,441619.0,30/09/2022,24/10/2022,286.00,0,8.451,0,277.549,0,NaN,NaN,NaN,21/10/2022,rm,0,$ -,10
Pocho,NaN,NaN,NaN,NaN,700.00,0,65.557,0,634.443,0,NaN,NaN,NaN,19/10/2022,RM,0,$ -,12
Pocho,BNA,832452.0,19/09/2022,15/11/2022,500.00,0,42.167,0,457.833,0,NaN,NaN,NaN,21/10/2022,RM Gordo,15000,$ -,11
Pocho,Macro,30107620.0,2/02/2022,8/11/2022,190.00,0,12.920,0,177.080,0,NaN,NaN,NaN,4/11/2022,CH,3800,$ -,11
Pocho,Macro,32111839.0,16/03/2022,17/11/2022,220.00,0,19.580,0,200.420,0,NaN,NaN,NaN,10/11/2022,rm,NaN,NaN,11
Pocho,Macro,33439802.0,24/05/2022,15/11/2022,400.00,0,32.800,0,367.200,0,NaN,NaN,NaN,19/10/2022,RM,0,$ -,11
Andrew,Galicia,65887770.0,18/10/2022,23/11/2022,291.70,0,41.700,0,250.000,0,NaN,NaN,NaN,4/11/2022,RMG,8751,$ -,11
Andrew,Galicia,65887771.0,18/10/2022,21/12/2022,291.70,0,41.700,0,250.000,0,NaN,NaN,NaN,10/11/2022,rmg,8751,NaN,12
Pablo H,Galicia,13515248.0,24/10/2022,4/11/2022,305.95,0,18.150,0,287.800,0,NaN,NaN,NaN,4/11/2022,CH,6119,$ -,11
Andrew,Galicia,65703763.0,22/10/2022,20/11/2022,141.60,0,16.600,0,125.000,0,NaN,NaN,NaN,4/11/2022,CH,4248,$ -,11
Andrew,Galicia,65703764.0,22/10/2022,21/11/2022,141.60,0,16.600,0,125.000,0,NaN,NaN,NaN,4/11/2022,RMG,4248,$ -,11
Andrew,Galicia,65703765.0,22/10/2022,20/12/2022,141.60,0,16.600,0,125.000,0,NaN,NaN,NaN,10/11/2022,ch,5664,NaN,12
Andrew,Galicia,65703766.0,22/10/2022,21/12/2022,141.60,0,16.600,0,125.000,0,NaN,NaN,NaN,10/11/2022,rmg,4248,NaN,12
Andrew,Galicia,65703767.0,22/10/2022,19/11/2022,150.00,0,25.000,0,125.000,0,NaN,NaN,NaN,10/11/2022,rm,NaN,NaN,11
Andrew,Galicia,65703768.0,22/10/2022,22/11/2022,150.00,0,25.000,0,125.000,0,NaN,NaN,NaN,4/11/2022,RM,4500,$ -,11
Andrew,Galicia,65703769.0,22/10/2022,19/12/2022,150.00,0,25.000,0,125.000,0,NaN,NaN,NaN,10/11/2022,rmg,4500,NaN,12
Andrew,Galicia,65703770.0,22/10/2022,22/12/2022,150.00,0,25.000,0,125.000,0,NaN,NaN,NaN,10/11/2022,ch,6000,NaN,12
Andrew,Galicia,65719911.0,24/10/2022,23/11/2022,150.35,0,25.350,0,125.000,0,NaN,NaN,NaN,4/11/2022,RMG,4510,$ -,11
Andrew,Galicia,65719912.0,24/10/2022,25/11/2022,150.35,0,25.350,0,125.000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
Andrew,Galicia,65719913.0,24/10/2022,23/12/2022,150.35,0,25.350,0,125.000,0,NaN,NaN,NaN,28/11/2022,ch,6012,NaN,12
Andrew,Galicia,65719914.0,24/10/2022,25/12/2022,150.35,0,25.350,0,125.000,0,NaN,NaN,NaN,28/11/2022,ch,6012,NaN,12
Pocho,Galicia,65887749.0,14/10/2022,11/11/2022,350.00,0,19.717,0,330.283,0,NaN,NaN,NaN,1/11/2022,CH,10500,$ -,11
Pocho,Galicia,65887750.0,14/10/2022,13/11/2022,350.00,0,21.350,0,328.650,0,NaN,NaN,NaN,1/11/2022,CH,10500,$ -,11
Pocho,Macro,31610719.0,24/09/2022,22/11/2022,226.00,0,18.532,0,207.468,0,NaN,NaN,NaN,4/11/2022,RMG,6780,$ -,11
Pocho,Macro,34486818.0,12/09/2022,20/11/2022,302.00,0,23.355,0,278.645,0,NaN,NaN,NaN,4/11/2022,RM,9060,$ -,11
Pocho,Macro,32533150.0,8/09/2022,26/11/2022,410.00,0,37.447,0,372.553,0,NaN,NaN,NaN,4/11/2022,RMG,12300,$ -,11
Pocho,Galicia,85192432.0,23/02/2022,23/11/2022,80.00,0,6.747,0,73.253,0,NaN,NaN,NaN,4/11/2022,RMG,2400,$ -,11
Andrew,Galicia,65703781.0,31/10/2022,5/01/2022,302.20,0,52.200,0,250.000,0,NaN,NaN,NaN,28/11/2022,ch,12888,NaN,1
Andrew,Galicia,65703782.0,31/10/2022,20/01/2022,302.20,0,52.200,0,250.000,0,NaN,NaN,NaN,17/11/2022,RM,SIN GASTOS,NaN,1
Andrew,Galicia,65703784.0,31/10/2022,6/01/2022,302.20,0,52.200,0,250.000,0,NaN,NaN,NaN,28/11/2022,ch,12888,NaN,1
Andrew,Galicia,65703785.0,31/10/2022,18/01/2022,302.20,0,52.200,0,250.000,0,NaN,NaN,NaN,17/11/2022,RM,SIN GASTOS,$ -,1

In [35]:
oct=oct.drop(['NRO CH/','T','E','M','EN CARTERA','Mes Ch'],axis=1)

In [36]:
oct=pd.DataFrame(oct)

In [37]:
oct

,CLIENTE,BANCO,F.EMIS,F.COBRO,IMPORTE,INTERESES,NETO,RECIBIDO,FECHA PAGO,DESCARGA,DESTINO,COSTO
Pocho,Macro,33342285.0,15/11/2022,165.00,0,16.225,0,148.775,0,10/11/2022,rm,NaN
Pocho,Bancor,32997251.0,7/11/2022,550.00,0,43.817,0,506.183,0,21/10/2022,RM Gordo,16500
Pocho,Santander,24200791.0,9/11/2022,650.00,0,54.817,0,595.183,0,21/10/2022,RM Gordo,19500
JL,BNA,441616.0,NaN,286.00,0,3.715,0,282.285,0,18/10/2022,JALIL,7150
JL,BNA,441619.0,24/10/2022,286.00,0,8.451,0,277.549,0,21/10/2022,rm,0
Pocho,NaN,NaN,NaN,700.00,0,65.557,0,634.443,0,19/10/2022,RM,0
Pocho,BNA,832452.0,15/11/2022,500.00,0,42.167,0,457.833,0,21/10/2022,RM Gordo,15000
Pocho,Macro,30107620.0,8/11/2022,190.00,0,12.920,0,177.080,0,4/11/2022,CH,3800
Pocho,Macro,32111839.0,17/11/2022,220.00,0,19.580,0,200.420,0,10/11/2022,rm,NaN
Pocho,Macro,33439802.0,15/11/2022,400.00,0,32.800,0,367.200,0,19/10/2022,RM,0
Andrew,Galicia,65887770.0,23/11/2022,291.70,0,41.700,0,250.000,0,4/11/2022,RMG,8751
Andrew,Galicia,65887771.0,21/12/2022,291.70,0,41.700,0,250.000,0,10/11/2022,rmg,8751
Pablo H,Galicia,13515248.0,4/11/2022,305.95,0,18.150,0,287.800,0,4/11/2022,CH,6119
Andrew,Galicia,65703763.0,20/11/2022,141.60,0,16.600,0,125.000,0,4/11/2022,CH,4248
Andrew,Galicia,65703764.0,21/11/2022,141.60,0,16.600,0,125.000,0,4/11/2022,RMG,4248
Andrew,Galicia,65703765.0,20/12/2022,141.60,0,16.600,0,125.000,0,10/11/2022,ch,5664
Andrew,Galicia,65703766.0,21/12/2022,141.60,0,16.600,0,125.000,0,10/11/2022,rmg,4248
Andrew,Galicia,65703767.0,19/11/2022,150.00,0,25.000,0,125.000,0,10/11/2022,rm,NaN
Andrew,Galicia,65703768.0,22/11/2022,150.00,0,25.000,0,125.000,0,4/11/2022,RM,4500
Andrew,Galicia,65703769.0,19/12/2022,150.00,0,25.000,0,125.000,0,10/11/2022,rmg,4500
Andrew,Galicia,65703770.0,22/12/2022,150.00,0,25.000,0,125.000,0,10/11/2022,ch,6000
Andrew,Galicia,65719911.0,23/11/2022,150.35,0,25.350,0,125.000,0,4/11/2022,RMG,4510
Andrew,Galicia,65719912.0,25/11/2022,150.35,0,25.350,0,125.000,0,NaN,NaN,NaN
Andrew,Galicia,65719913.0,23/12/2022,150.35,0,25.350,0,125.000,0,28/11/2022,ch,6012
Andrew,Galicia,65719914.0,25/12/2022,150.35,0,25.350,0,125.000,0,28/11/2022,ch,6012
Pocho,Galicia,65887749.0,11/11/2022,350.00,0,19.717,0,330.283,0,1/11/2022,CH,10500
Pocho,Galicia,65887750.0,13/11/2022,350.00,0,21.350,0,328.650,0,1/11/2022,CH,10500
Pocho,Macro,31610719.0,22/11/2022,226.00,0,18.532,0,207.468,0,4/11/2022,RMG,6780
Pocho,Macro,34486818.0,20/11/2022,302.00,0,23.355,0,278.645,0,4/11/2022,RM,9060
Pocho,Macro,32533150.0,26/11/2022,410.00,0,37.447,0,372.553,0,4/11/2022,RMG,12300
Pocho,Galicia,85192432.0,23/11/2022,80.00,0,6.747,0,73.253,0,4/11/2022,RMG,2400
Andrew,Galicia,65703781.0,5/01/2022,302.20,0,52.200,0,250.000,0,28/11/2022,ch,12888
Andrew,Galicia,65703782.0,20/01/2022,302.20,0,52.200,0,250.000,0,17/11/2022,RM,SIN GASTOS
Andrew,Galicia,65703784.0,6/01/2022,302.20,0,52.200,0,250.000,0,28/11/2022,ch,12888
Andrew,Galicia,65703785.0,18/01/2022,302.20,0,52.200,0,250.000,0,17/11/2022,RM,SIN GASTOS

In [16]:
oct.describe()

          F.COBRO  IMPORTE  INTERESES  NETO     RECIBIDO  FECHA PAGO
count   35.000000     35.0  35.000000   35.0   35.000000        35.0
mean   272.312857      0.0  28.724200    0.0  243.588657         0.0
std    149.154682      0.0  15.490036    0.0  139.150860         0.0
min     80.000000      0.0   3.715000    0.0   73.253000         0.0
25%    150.175000      0.0  17.375000    0.0  125.000000         0.0
50%    286.000000      0.0  25.000000    0.0  250.000000         0.0
75%    304.075000      0.0  41.700000    0.0  285.042500         0.0
max    700.000000      0.0  65.557000    0.0  634.443000         0.0

In [38]:
pd.pivot_table(oct,index=['CLIENTE'])

,BANCO,F.COBRO,FECHA PAGO,IMPORTE,INTERESES,NETO,RECIBIDO
CLIENTE,,,,,,,
BNA,5.718957e+05,357.333333,0,0,18.111000,0,339.222333
Bancor,3.299725e+07,550.000000,0,0,43.817000,0,506.183000
Galicia,6.425380e+07,211.179545,0,0,28.452909,0,182.726636
Macro,3.251889e+07,273.285714,0,0,22.979857,0,250.305857
Santander,2.420079e+07,650.000000,0,0,54.817000,0,595.183000

In [39]:
oct['CLIENTE']

Pocho          Macro
Pocho         Bancor
Pocho      Santander
JL               BNA
JL               BNA
Pocho            NaN
Pocho            BNA
Pocho          Macro
Pocho          Macro
Pocho          Macro
Andrew       Galicia
Andrew       Galicia
Pablo H      Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Pocho        Galicia
Pocho        Galicia
Pocho          Macro
Pocho          Macro
Pocho          Macro
Pocho        Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Andrew       Galicia
Name: CLIENTE, dtype: object

In [40]:
!cat 'octubre.csv'

CLIENTE,BANCO,NRO CH/,F.EMIS,F.COBRO,IMPORTE,INTERESES,NETO ,RECIBIDO,FECHA PAGO,T,E,M,DESCARGA,DESTINO,COSTO,EN CARTERA,Mes Ch
Pocho,Macro,33342285,13/05/2022,15/11/2022,165.000,00 ,16.225,00 ,148.775,00 ,13-oct,,,10/11/2022,rm,,,11
Pocho,Bancor,32997251,11/10/2022,7/11/2022,550.000,00 ,43.817,00 ,506.183,00 ,13-oct,,,21/10/2022,RM Gordo,16500, $  -   ,11
Pocho,Santander,24200791,6/10/2022,9/11/2022,650.000,00 ,54.817,00 ,595.183,00 ,13-oct,,,21/10/2022,RM Gordo,19500, $  -   ,11
JL,BNA,441616,,,286.000,00 ,3.715,00 ,282.285,00 ,,,,18/10/2022,JALIL,7150, $  -   ,12
JL,BNA,441619,30/09/2022,24/10/2022,286.000,00 ,8.451,00 ,277.549,00 ,,,,21/10/2022,rm,0, $  -   ,10
Pocho,,,,,700.000,00 ,65.557,00 ,634.443,00 ,,,,19/10/2022,RM,0, $  -   ,12
Pocho,BNA,832452,19/09/2022,15/11/2022,500.000,00 ,42.167,00 ,457.833,00 ,,,,21/10/2022,RM Gordo,15000, $  -   ,11
Pocho,Macro,30107620,2/02/2022,8/11/2022,190.000,00 ,12.920,00 ,177.080,00 ,,,,4/11/2022,CH,3800, $  -   ,11
Pocho,Macro,32111839,16/03/2022,17/11/2022,220.000,00 ,19.580,00 ,200.420,00 ,,,,10/11/2022, rm ,,,11
Pocho,Macro,33439802,24/05/2022,15/11/2022,400.000,00 ,32.800,00 ,367.200,00 ,,,,19/10/2022, RM ,0, $  -   ,11
Andrew,Galicia,65887770,18/10/2022,23/11/2022,291.700,00 ,41.700,00 ,250.000,00 ,,,,4/11/2022, RMG ,8751, $  -   ,11
Andrew,Galicia,65887771,18/10/2022,21/12/2022,291.700,00 ,41.700,00 ,250.000,00 ,,,,10/11/2022, rmg ,8751,,12
Pablo H,Galicia,13515248,24/10/2022,4/11/2022,305.950,00 ,18.150,00 ,287.800,00 ,,,,4/11/2022, CH ,6119, $  -   ,11
Andrew,Galicia,65703763,22/10/2022,20/11/2022,141.600,00 ,16.600,00 ,125.000,00 ,,,,4/11/2022, CH ,4248, $  -   ,11
Andrew,Galicia,65703764,22/10/2022,21/11/2022,141.600,00 ,16.600,00 ,125.000,00 ,,,,4/11/2022, RMG ,4248, $  -   ,11
Andrew,Galicia,65703765,22/10/2022,20/12/2022,141.600,00 ,16.600,00 ,125.000,00 ,,,,10/11/2022,ch,5664,,12
Andrew,Galicia,65703766,22/10/2022,21/12/2022,141.600,00 ,16.600,00 ,125.000,00 ,,,,10/11/2022,rmg,4248,,12
Andrew,Galicia,65703767,22/10/2022,19/11/2022,150.000,00 ,25.000,00 ,125.000,00 ,,,,10/11/2022,rm,,,11
Andrew,Galicia,65703768,22/10/2022,22/11/2022,150.000,00 ,25.000,00 ,125.000,00 ,,,,4/11/2022,RM,4500, $  -   ,11
Andrew,Galicia,65703769,22/10/2022,19/12/2022,150.000,00 ,25.000,00 ,125.000,00 ,,,,10/11/2022,rmg,4500,,12
Andrew,Galicia,65703770,22/10/2022,22/12/2022,150.000,00 ,25.000,00 ,125.000,00 ,,,,10/11/2022,ch,6000,,12
Andrew,Galicia,65719911,24/10/2022,23/11/2022,150.350,00 ,25.350,00 ,125.000,00 ,,,,4/11/2022,RMG,4510, $  -   ,11
Andrew,Galicia,65719912,24/10/2022,25/11/2022,150.350,00 ,25.350,00 ,125.000,00 ,,,,,,,,11
Andrew,Galicia,65719913,24/10/2022,23/12/2022,150.350,00 ,25.350,00 ,125.000,00 ,,,,28/11/2022,ch,6012,,12
Andrew,Galicia,65719914,24/10/2022,25/12/2022,150.350,00 ,25.350,00 ,125.000,00 ,,,,28/11/2022,ch,6012,,12
Pocho,Galicia,65887749,14/10/2022,11/11/2022,350.000,00 ,19.717,00 ,330.283,00 ,,,,1/11/2022,CH,10500, $  -   ,11
Pocho,Galicia,65887750,14/10/2022,13/11/2022,350.000,00 ,21.350,00 ,328.650,00 ,,,,1/11/2022,CH,10500, $  -   ,11
Pocho,Macro,31610719,24/09/2022,22/11/2022,226.000,00 ,18.532,00 ,207.468,00 ,,,,4/11/2022,RMG,6780, $  -   ,11
Pocho,Macro,34486818,12/09/2022,20/11/2022,302.000,00 ,23.355,00 ,278.645,00 ,,,,4/11/2022,RM,9060, $  -   ,11
Pocho,Macro,32533150,8/09/2022,26/11/2022,410.000,00 ,37.447,00 ,372.553,00 ,,,,4/11/2022,RMG,12300, $  -   ,11
Pocho,Galicia,85192432,23/02/2022,23/11/2022,80.000,00 ,6.747,00 ,73.253,00 ,,,,4/11/2022,RMG,2400, $  -   ,11
Andrew,Galicia,65703781,31/10/2022,5/01/2022,302.200,00 ,52.200,00 ,250.000,00 ,,,,28/11/2022,ch,12888,,1
Andrew,Galicia,65703782,31/10/2022,20/01/2022,302.200,00 ,52.200,00 ,250.000,00 ,,,,17/11/2022,RM,SIN GASTOS,,1
Andrew,Galicia,65703784,31/10/2022,6/01/2022,302.200,00 ,52.200,00 ,250.000,00 ,,,,28/11/2022,ch,12888,,1
Andrew,Galicia,65703785,31/10/2022,18/01/2022,302.200,00 ,52.200,00 ,250.000,00 ,,,,17/11/2022,RM,SIN GASTOS, $  -   ,1