In [5]:
import pandas as pd
import numpy as np

In [6]:
cd /home/marco/Metricas\ VE

/home/marco/Metricas VE

In [27]:
ls

CD_cupos.csv  CD_paquetes.csv  CD_producto.csv  CD_vuelos.csv  Untitled.ipynb

In [28]:
cupos = pd.read_csv('CD_cupos.csv')

In [41]:
paquetes = pd.read_csv('CD_paquetes.csv')

In [30]:
producto = pd.read_csv('CD_producto.csv')

In [31]:
vuelos = pd.read_csv('CD_vuelos.csv')

In [42]:
print(vuelos,paquetes,producto,cupos)

   Ubicación de consecución de objetivos Unnamed: 1
0                                 delfos         11
1                             nikanttour          9
2                        universalviajes          7
3                            wairatravel          5
4                               avallone          3
5                     dubaiviajesgralpaz          3
6                           KaizenViajes          3
7         blancofranquiciadelozadaviajes          2
8              borniegoviajesyturismoevt          2
9                 caofranquiciadeonetrip          2
10                           croisviajes          2
11                          eltopoviajes          2
12                      miradordelnevado          2
13                           naivaviajes          2
14                               onetrip        NaN
15                          SelvaExtrema          2
16                        tallerdeviajes          2
17                     turismocaupolican          2
18                        turismoenserie          2
19                         TURISMOMUTUAL          2
20                            tuyuviajes          2
21                               7noches          1
22                          agapeturismo        NaN
23                             allgroups          1
24                               alticla          1
25                              argentur          1
26                       babelvillamaria          1
27        bustosfranquiciadelozadaviajes          1
28                             chipotour          1
29                                chucao          1
30     clubatleticosanjorgemutualysocial          1
31                     cordobatredtravel          1
32                          cosmopolitan          1
33                           cultutravel          1
34                        delfosparaguay          1
35                               deviene          1
36                             docviajes          1
37                       elpoderdeviajar          1
38                    flugviajesyturismo          1
39                             geomundos          1
40                       gracielaudrisar          1
41                             gramitour          1
42                    himalayacordillera          1
43                         hubelamviajes          1
44                        incananturismo          1
45                                indico          1
46                             jacaranda          1
47                           laspalmeras          1
48                           majestytour          1
49                      miradordelnevado     LVE53E
50                                   124        NaN         Ubicación de consecución de objetivos  Unnamed: 1
0                                      delfos        30.0
1                                KaizenViajes         9.0
2   proyectosviajerosfranquiciadelozadaviajes         7.0
3                                  butelerevt         6.0
4                       himalayaviajescordoba         6.0
5                                     onetrip         5.0
6                             andesmarturismo         4.0
7                 cahinhueserviciosturisticos         4.0
8                                    freeport         4.0
9                                 ceiboviajes         3.0
10                               claseturista         3.0
11                                  crdtravel         3.0
12                                     delfos         3.0
13                              LIVIGNOVIAJES         3.0
14                                 nanatravel         3.0
15                       onetripvillabelgrano         3.0
16                   ramonmartintravelservice         3.0
17                 tosellifranquiciadeonetrip         3.0
18                                  altapampa         2.0
19                    benzaquenviajesyturismo         2.0
20                                 chipretour         2.0
21                      cuareimviajesyturismo         2.0
22              elekserviciosdeviajesyturismo         2.0
23           grupounofranquiciadelozadaviajes         2.0
24          linaevansfranquiciadelozadaviajes         2.0
25                       lozadaviajessouberan         2.0
26                                   maitreya         2.0
27             maneiroempresadeviajesyturismo         2.0
28                          marcoantoniotours         2.0
29                           onetripsancarlos         2.0
..                                        ...         ...
58                                  grupolive         1.0
59                   himalayaviajesgeneralpaz         1.0
60                     ketrascargoargentinasa         1.0
61                    labrujulaviajesyturismo         1.0
62                                losterrones         1.0
63                                majestytour         1.0
64                               mariniviajes         1.0
65                                marioaguero         1.0
66                           moaiviajesnvacba         1.0
67                                   MONEYTUR         1.0
68                    mutualfederada25dejunio         1.0
69                               newbiztravel         1.0
70                                    onetrip         NaN
71                                    onetrip         NaN
72                                    onetrip         NaN
73                                    onetrip         1.0
74                             onetripdelbono         1.0
75                          onetripgeneralpaz         1.0
76                        onetripvillaallende         1.0
77                           parakaloviajemos         1.0
78                          SuryViajesAustral         1.0
79                             tallerdeviajes         1.0
80                              tourneeviajes         1.0
81                                travelwings         1.0
82                               turismobacur         1.0
83                          turismovittoriosj         1.0
84                                 tuyuviajes         1.0
85                            viajarenunclick         1.0
86                              windtravelers         1.0
87                              zanierturismo         NaN

[88 rows x 2 columns]    Ubicación de consecución de objetivos  Unnamed: 1
0                              luaviajes         4.0
1            cahinhueserviciosturisticos         2.0
2                                onetrip         2.0
3                                audamar         1.0
4                               avallone         1.0
5                        baturiteturismo         1.0
6                             butelerevt         1.0
7            cahinhueserviciosturisticos         1.0
8                 caofranquiciadeonetrip         1.0
9                                deviene         1.0
10                             dwtviajes         1.0
11                            extremosur         1.0
12                           gruporolsol         1.0
13                 himalayaviajescordoba         1.0
14              himalayaviajesgeneralpaz         1.0
15                                 izlet         1.0
16                         LIVIGNOVIAJES         1.0
17                lozadaviajesexclusivos         1.0
18                           majestytour         1.0
19                          mariniviajes         1.0
20                   martaniaviajesmaipu         1.0
21                            mioturismo         1.0
22                            nanatravel         1.0
23             oniriaserviciosturisticos         1.0
24                         pelossotravel         1.0
25                      tisseraviajescom         1.0
26                      tisseraviajescom         1.0
27                         TURISMOMUTUAL         1.0
28                          vablaturismo         1.0
29                           vetedeviaje         1.0
30                 viajestdhbjardincerro         1.0
31                                    36         NaN    Ubicación de consecución de objetivos  Unnamed: 1
0              atokosexperienciasdeviaje         1.0
1                benzaquenviajesyturismo         1.0
2                benzaquenviajesyturismo         1.0
3                benzaquenviajesyturismo         1.0
4                benzaquenviajesyturismo         1.0
5                benzaquenviajesyturismo         1.0
6                           bernaltravel         1.0
7                 caofranquiciadeonetrip         1.0
8                           claseturista         1.0
9                           claseturista         1.0
10                                delfos         1.0
11                                delfos         1.0
12                                delfos         1.0
13                                delfos         1.0
14                                delfos         1.0
15                                delfos         1.0
16                                delfos         1.0
17                                delfos         1.0
18                                delfos         1.0
19                                delfos         1.0
20                                delfos         1.0
21                                delfos         1.0
22                                delfos         1.0
23                                delfos         1.0
24                                delfos         1.0
25                                delfos         1.0
26                             dipviajes         1.0
27                            divinitrip         1.0
28                              grupomas         1.0
29                    grupoochooperadora         1.0
30                 himalayaviajescordoba         1.0
31       iconicafranquiciadelozadaviajes         1.0
32                          KaizenViajes         1.0
33               lozadaviajescasacentral         1.0
34                         manadaviajera         1.0
35                         neuquentravel         1.0
36                               onetrip         1.0
37                             sunflower         1.0
38                        tallerdeviajes         1.0
39                         taxfreetravel         1.0
40                    testviajesyturismo         1.0
41                                    41         NaN

In [43]:
vuelos.describe()

       Ubicación de consecución de objetivos Unnamed: 1
count                                     51         48
unique                                    50          8
top                         miradordelnevado          1
freq                                       2         27

In [44]:
cupos.describe()

       Unnamed: 1
count        41.0
mean          1.0
std           0.0
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           1.0

In [45]:
producto.describe()

       Unnamed: 1
count   31.000000
mean     1.161290
std      0.582911
min      1.000000
25%      1.000000
50%      1.000000
75%      1.000000
max      4.000000

In [46]:
paquetes.describe()

       Unnamed: 1
count   79.000000
mean     2.227848
std      3.515349
min      1.000000
25%      1.000000
50%      1.000000
75%      2.000000
max     30.000000

In [47]:
vuelos.index, paquetes.index, producto.index, cupos.index

(RangeIndex(start=0, stop=51, step=1),
 RangeIndex(start=0, stop=88, step=1),
 RangeIndex(start=0, stop=32, step=1),
 RangeIndex(start=0, stop=42, step=1))

In [48]:
print(vuelos)

   Ubicación de consecución de objetivos Unnamed: 1
0                                 delfos         11
1                             nikanttour          9
2                        universalviajes          7
3                            wairatravel          5
4                               avallone          3
5                     dubaiviajesgralpaz          3
6                           KaizenViajes          3
7         blancofranquiciadelozadaviajes          2
8              borniegoviajesyturismoevt          2
9                 caofranquiciadeonetrip          2
10                           croisviajes          2
11                          eltopoviajes          2
12                      miradordelnevado          2
13                           naivaviajes          2
14                               onetrip        NaN
15                          SelvaExtrema          2
16                        tallerdeviajes          2
17                     turismocaupolican          2
18                        turismoenserie          2
19                         TURISMOMUTUAL          2
20                            tuyuviajes          2
21                               7noches          1
22                          agapeturismo        NaN
23                             allgroups          1
24                               alticla          1
25                              argentur          1
26                       babelvillamaria          1
27        bustosfranquiciadelozadaviajes          1
28                             chipotour          1
29                                chucao          1
30     clubatleticosanjorgemutualysocial          1
31                     cordobatredtravel          1
32                          cosmopolitan          1
33                           cultutravel          1
34                        delfosparaguay          1
35                               deviene          1
36                             docviajes          1
37                       elpoderdeviajar          1
38                    flugviajesyturismo          1
39                             geomundos          1
40                       gracielaudrisar          1
41                             gramitour          1
42                    himalayacordillera          1
43                         hubelamviajes          1
44                        incananturismo          1
45                                indico          1
46                             jacaranda          1
47                           laspalmeras          1
48                           majestytour          1
49                      miradordelnevado     LVE53E
50                                   124        NaN

In [49]:
print(paquetes)

        Ubicación de consecución de objetivos  Unnamed: 1
0                                      delfos        30.0
1                                KaizenViajes         9.0
2   proyectosviajerosfranquiciadelozadaviajes         7.0
3                                  butelerevt         6.0
4                       himalayaviajescordoba         6.0
5                                     onetrip         5.0
6                             andesmarturismo         4.0
7                 cahinhueserviciosturisticos         4.0
8                                    freeport         4.0
9                                 ceiboviajes         3.0
10                               claseturista         3.0
11                                  crdtravel         3.0
12                                     delfos         3.0
13                              LIVIGNOVIAJES         3.0
14                                 nanatravel         3.0
15                       onetripvillabelgrano         3.0
16                   ramonmartintravelservice         3.0
17                 tosellifranquiciadeonetrip         3.0
18                                  altapampa         2.0
19                    benzaquenviajesyturismo         2.0
20                                 chipretour         2.0
21                      cuareimviajesyturismo         2.0
22              elekserviciosdeviajesyturismo         2.0
23           grupounofranquiciadelozadaviajes         2.0
24          linaevansfranquiciadelozadaviajes         2.0
25                       lozadaviajessouberan         2.0
26                                   maitreya         2.0
27             maneiroempresadeviajesyturismo         2.0
28                          marcoantoniotours         2.0
29                           onetripsancarlos         2.0
..                                        ...         ...
58                                  grupolive         1.0
59                   himalayaviajesgeneralpaz         1.0
60                     ketrascargoargentinasa         1.0
61                    labrujulaviajesyturismo         1.0
62                                losterrones         1.0
63                                majestytour         1.0
64                               mariniviajes         1.0
65                                marioaguero         1.0
66                           moaiviajesnvacba         1.0
67                                   MONEYTUR         1.0
68                    mutualfederada25dejunio         1.0
69                               newbiztravel         1.0
70                                    onetrip         NaN
71                                    onetrip         NaN
72                                    onetrip         NaN
73                                    onetrip         1.0
74                             onetripdelbono         1.0
75                          onetripgeneralpaz         1.0
76                        onetripvillaallende         1.0
77                           parakaloviajemos         1.0
78                          SuryViajesAustral         1.0
79                             tallerdeviajes         1.0
80                              tourneeviajes         1.0
81                                travelwings         1.0
82                               turismobacur         1.0
83                          turismovittoriosj         1.0
84                                 tuyuviajes         1.0
85                            viajarenunclick         1.0
86                              windtravelers         1.0
87                              zanierturismo         NaN

[88 rows x 2 columns]

In [51]:
print(producto)

   Ubicación de consecución de objetivos  Unnamed: 1
0                              luaviajes         4.0
1            cahinhueserviciosturisticos         2.0
2                                onetrip         2.0
3                                audamar         1.0
4                               avallone         1.0
5                        baturiteturismo         1.0
6                             butelerevt         1.0
7            cahinhueserviciosturisticos         1.0
8                 caofranquiciadeonetrip         1.0
9                                deviene         1.0
10                             dwtviajes         1.0
11                            extremosur         1.0
12                           gruporolsol         1.0
13                 himalayaviajescordoba         1.0
14              himalayaviajesgeneralpaz         1.0
15                                 izlet         1.0
16                         LIVIGNOVIAJES         1.0
17                lozadaviajesexclusivos         1.0
18                           majestytour         1.0
19                          mariniviajes         1.0
20                   martaniaviajesmaipu         1.0
21                            mioturismo         1.0
22                            nanatravel         1.0
23             oniriaserviciosturisticos         1.0
24                         pelossotravel         1.0
25                      tisseraviajescom         1.0
26                      tisseraviajescom         1.0
27                         TURISMOMUTUAL         1.0
28                          vablaturismo         1.0
29                           vetedeviaje         1.0
30                 viajestdhbjardincerro         1.0
31                                    36         NaN

In [52]:
producto(producto.nan(Nan='1'))

AttributeError: 'DataFrame' object has no attribute 'nan'

In [54]:
busquedas=pd.read_csv('busquedas.csv')

In [69]:
print(busquedas)

                             Página   Total de eventos Eventos únicos  \
0                        coruniasur  cotizador-offline           home
1                   viajarenunclick  cotizador-offline           home
2            caofranquiciadeonetrip  cotizador-offline           home
3                       ceiboviajes  cotizador-offline           home
4                        coruniasur  cotizador-offline           home
5                       croisviajes  cotizador-offline           home
6                            delfos  cotizador-offline           home
7            caofranquiciadeonetrip  cotizador-offline           home
8            caofranquiciadeonetrip  cotizador-offline           home
9                       ceiboviajes  cotizador-offline           home
10                           delfos  cotizador-offline           home
11                         freeport  cotizador-offline           home
12                             goup  cotizador-offline           home
13                        grupolive  cotizador-offline           home
14                    LIVIGNOVIAJES  cotizador-offline           home
15                    LIVIGNOVIAJES  cotizador-offline           home
16                     parmeturismo  cotizador-offline           home
17                      VINEAVIAJES  cotizador-offline           home
18                         avallone             vuelos     resultados
19          babiloniaviajesyturismo  cotizador-offline           home
20          babiloniaviajesyturismo  cotizador-offline           home
21   bustosfranquiciadelozadaviajes  cotizador-offline           home
22      cahinhueserviciosturisticos             vuelos     resultados
23           caofranquiciadeonetrip  cotizador-offline           home
24           caofranquiciadeonetrip  cotizador-offline           home
25           caofranquiciadeonetrip  cotizador-offline           home
26                           chucao  cotizador-offline           home
27                       coruniasur  cotizador-offline           home
28                       coruniasur  cotizador-offline           home
29                     cosmopolitan  cotizador-offline           home
..                              ...                ...            ...
628             viajestdhgeneralpaz  cotizador-offline           home
629                  viarolyturismo  cotizador-offline           home
630                     VINEAVIAJES  cotizador-offline           home
631                     VINEAVIAJES  cotizador-offline           home
632                     VINEAVIAJES  cotizador-offline           home
633                     VINEAVIAJES  cotizador-offline           home
634                     VINEAVIAJES  cotizador-offline           home
635                     VINEAVIAJES  cotizador-offline           home
636                     VINEAVIAJES  cotizador-offline           home
637                     VINEAVIAJES  cotizador-offline           home
638                     VINEAVIAJES  cotizador-offline           home
639                     VINEAVIAJES  cotizador-offline           home
640                     VINEAVIAJES  cotizador-offline           home
641                     VINEAVIAJES  cotizador-offline           home
642                     VINEAVIAJES  cotizador-offline           home
643                          vorano  cotizador-offline           home
644                          vorano  cotizador-offline           home
645                vuelevueleonline  cotizador-offline           home
646                    zeruanviajes  cotizador-offline           home
647                    zeruanviajes  cotizador-offline           home
648                    zeruanviajes  cotizador-offline           home
649                    zeruanviajes  cotizador-offline           home
650                    zeruanviajes  cotizador-offline           home
651                    zeruanviajes  cotizador-offline           home
652                    zeruanviajes  cotizador-offline           home
653                    zeruanviajes  cotizador-offline           home
654                   zonadepartida  cotizador-offline           home
655                   zonadepartida  cotizador-offline           home
656                   zonadepartida  cotizador-offline           home
657                   zonadepartida  cotizador-offline           home

    Valor del evento Valor medio  Unnamed: 5                 Unnamed: 6  \
0         resultados         NAT  12-08-2018                 17-08-2018
1         resultados         MIA  25-10-2018                 31-10-2018
2         resultados         HAV  03-07-2018                 31-07-2018
3         resultados         PCM  22-05-2018                 29-05-2018
4         resultados         IGR  24-04-2018                 27-04-2018
5         resultados         BYH  06-06-2018                 16-06-2018
6         resultados         PRF  24-04-2018                 31-10-2018
7         resultados         IMB  15-08-2018                 22-08-2018
8         resultados         SSA  15-08-2018                 22-08-2018
9         resultados         ADZ  30-05-2018                 07-06-2018
10        resultados         PRF  27-04-2018                 30-11-2018
11        resultados         PUJ  11-07-2018                 19-07-2018
12        resultados         PTY  09-05-2018                 31-05-2018
13        resultados         CTG  11-09-2018                 19-09-2018
14        resultados         PBI  01-07-2018  27-07-2018?tipo=productos
15        resultados         PUJ  01-11-2018                 30-11-2018
16        resultados         HAV  05-06-2018                 07-06-2018
17        resultados         PTY  12-08-2018                 18-08-2018
18               MDZ         IGR  10-07-2018       13-07-2018?adultos=2
19        resultados         CSM  14-12-2018                 21-12-2018
20        resultados         PUJ  22-12-2018                 29-12-2018
21        resultados         CUN  17-05-2018                 26-05-2018
22               MDZ         CTG  04-03-2019       13-03-2019?adultos=2
23        resultados         POR  01-07-2018                 31-07-2018
24        resultados         PUJ  03-09-2018                 10-09-2018
25        resultados         VRA  01-12-2018                 31-12-2018
26        resultados         PTY  08-11-2018  15-11-2018?tipo=productos
27        resultados         IGU  24-04-2018                 27-04-2018
28        resultados         SSA  18-09-2018                 26-09-2018
29        resultados         BZC  09-11-2018                 17-11-2018
..               ...         ...         ...                        ...
628       resultados         FTE  02-08-2018                 31-08-2018
629       resultados         PUJ  09-06-2018                 20-06-2018
630       resultados         BKK  13-11-2018                 15-11-2018
631       resultados         CUN  20-06-2018                 30-06-2018
632       resultados         HAV  17-07-2018                 19-07-2018
633       resultados         MEX  11-07-2018                 15-07-2018
634       resultados         MEX  20-06-2018                 22-06-2018
635       resultados         MEX  20-06-2018                 30-06-2018
636       resultados         NAT  02-12-2018                 07-12-2018
637       resultados         NYC  12-08-2018                 18-08-2018
638       resultados         PCM  15-07-2018                 22-07-2018
639       resultados         PTY  09-06-2018                 23-06-2018
640       resultados         PUJ  02-12-2018                 07-12-2018
641       resultados         SCL  25-04-2018                 26-04-2018
642       resultados         VRA  17-07-2018                 19-07-2018
643       resultados         GIG  12-08-2018                 31-08-2018
644       resultados         RIO  12-08-2018                 31-08-2018
645       resultados         MBJ  27-12-2018                 06-01-2019
646       resultados         BYH  14-05-2018                 23-05-2018
647       resultados         BYH  14-08-2018                 23-08-2018
648       resultados         MGG  14-07-2018                 27-07-2018
649       resultados         MGG  19-07-2018                 27-07-2018
650       resultados         PUJ  14-07-2018                 27-07-2018
651       resultados         ROM  15-08-2018                 16-08-2018
652       resultados         ROM  15-08-2018                 30-08-2018
653       resultados         SSA  19-07-2018                 27-07-2018
654       resultados         AKM  22-12-2018                 29-12-2018
655       resultados         POR  20-05-2018                 26-05-2018
656       resultados         POR  27-06-2018                 04-07-2018
657       resultados         RIO  25-12-2018                 04-01-2019

     Unnamed: 7  Unnamed: 8  Unnamed: 9
0           0.0         0.0         0.0
1           1.0         0.0         0.0
2           0.0         0.0         0.0
3           1.0         0.0         0.0
4           1.0         0.0         0.0
5           3.0         0.0         0.0
6           1.0         0.0         0.0
7           1.0         0.0         0.0
8           0.0         0.0         0.0
9           2.0         0.0         0.0
10          0.0         0.0         0.0
11          1.0         0.0         0.0
12          1.0         0.0         0.0
13          3.0         0.0         0.0
14          1.0         0.0         0.0
15          1.0         0.0         0.0
16          3.0         0.0         0.0
17          1.0         0.0         0.0
18          1.0         0.0         0.0
19          0.0         0.0         0.0
20          2.0         0.0         0.0
21          1.0         0.0         0.0
22          1.0         0.0         0.0
23          2.0         0.0         0.0
24          1.0         0.0         0.0
25          0.0         0.0         0.0
26          1.0         0.0         0.0
27          1.0         0.0         0.0
28          2.0         0.0         0.0
29          2.0         0.0         0.0
..          ...         ...         ...
628         0.0         0.0         0.0
629         0.0         0.0         0.0
630         1.0         0.0         0.0
631         0.0         0.0         0.0
632         1.0         0.0         0.0
633         0.0         0.0         0.0
634         1.0         0.0         0.0
635         1.0         0.0         0.0
636         0.0         0.0         0.0
637         0.0         0.0         0.0
638         1.0         0.0         0.0
639         1.0         0.0         0.0
640         0.0         0.0         0.0
641         1.0         0.0         0.0
642         0.0         0.0         0.0
643         1.0         0.0         0.0
644         0.0         0.0         0.0
645         1.0         0.0         0.0
646         1.0         0.0         0.0
647         0.0         0.0         0.0
648         1.0         0.0         0.0
649         0.0         0.0         0.0
650         1.0         0.0         0.0
651         1.0         0.0         0.0
652         0.0         0.0         0.0
653         1.0         0.0         0.0
654         1.0         0.0         0.0
655         1.0         0.0         0.0
656         1.0         0.0         0.0
657         1.0         0.0         0.0

[658 rows x 10 columns]

In [85]:
print(busquedas.loc[busquedas['Valor medio'].str.contains('ADZ'),['Página','Valor medio']])

                             Página Valor medio
9                       ceiboviajes         ADZ
48                    LIVIGNOVIAJES         ADZ
67               virginiaruiturismo         ADZ
86                      animatravel         ADZ
99          babiloniaviajesyturismo         ADZ
155                     ceiboviajes         ADZ
262                         essenya         ADZ
285                  gabrielapistek         ADZ
286                  gabrielapistek         ADZ
358                     grupolozada         ADZ
359                     grupolozada         ADZ
360                     grupolozada         ADZ
378           himalayaviajescordoba         ADZ
379           himalayaviajescordoba         ADZ
382                          huilen         ADZ
416                laalcarriaviajes         ADZ
444                        lifetrip         ADZ
462          lozadaviajesexclusivos         ADZ
470  machucafortefranquiciadelozada         ADZ
471  machucafortefranquiciadelozada         ADZ
476              maresdelsurturismo         ADZ
495                mendozawinetours         ADZ
498                     namurviajes         ADZ
534                onetripcarlospaz         ADZ
535                onetripcarlospaz         ADZ
549                onetripsancarlos         ADZ
558            onetripvillabelgrano         ADZ
611                     travelfresh         ADZ